version: '3'

services:
    eureka:
        build:
            context: ./
            dockerfile: ./eureka/Dockerfile
        # image: springcloud/eureka
        ports:
        #     - "8080:8080"
            - "8761:8761"
    zuul:
        build:
            context: ./
            dockerfile: ./zuul/Dockerfile
        # image: netflixoss/zuul:1.0.28
        ports: 
            - "8080:8080"
        depends_on:
            - "eureka"
    gateway: 
        build:
            context: ./
            dockerfile: ./packages/gateway/Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - "eureka"
            - "zuul"
    users: 
        build:
            context: ./
            dockerfile: ./packages/users/Dockerfile
        ports:
            - "3004:3004"
        links:
            - mongo
        depends_on:
            - "eureka"
            - "zuul"
            - "mongo"
    locations: 
        build:
            context: ./
            dockerfile: ./packages/locations/Dockerfile
        ports:
            - "3001:3001"
        links:
            - mongo
        depends_on:
            - "eureka"
            - "zuul"
            - "mongo"
    proposals: 
        build:
            context: ./
            dockerfile: ./packages/proposals/Dockerfile
        ports:
            - "3002:3002"
        links:
            - mongo
        depends_on:
            - "eureka"
            - "zuul"
            - "mongo" 
    reviews: 
        build:
            context: ./
            dockerfile: ./packages/reviews/Dockerfile
        ports:
            - "3003:3003"
        links:
            - mongo
        depends_on:
            - "eureka"
            - "zuul"
            - "mongo"
    mongo:
        image: mvertes/alpine-mongo
        volumes:
            -  C:\Users\Deborah\docker\mongodb-data:/data/db
        ports: 
            - "27017:27017"


